import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Loader from "./loading";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Jasmeen Desai",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container">
          <Navbar/>
        {children}
        </div>
        
        </body>
    </html>
  );
}
